spring.application.name=workhub

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=${env.DB_URL}
spring.datasource.username=${env.DB_USER}
spring.datasource.password=${env.DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# ===============================
# JWT Configuration
# ===============================
jwt.secret=${env.JWT_SECRET}

env.printer.enabled=false


